# Generated by Django 5.2.7 on 2025-10-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id_ride', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('pickup_latitude', models.FloatField(max_length=12)),
                ('pickup_longitude', models.FloatField(max_length=12)),
                ('dropoff_latitude', models.FloatField(max_length=12)),
                ('dropoff_longitude', models.FloatField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ride_Event',
            fields=[
                ('id_ride_event', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ride')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='id_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_driver', to='api.user'),
        ),
        migrations.AddField(
            model_name='ride',
            name='id_rider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rider', to='api.user'),
        ),
    ]
