# Generated by Django 5.2.7 on 2025-10-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ride_status_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='id_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_events', to='api.ride'),
        ),
    ]
