# Generated by Django 5.2.7 on 2025-10-22 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ride_Event',
            new_name='RideEvent',
        ),
    ]
