# Generated by Django 5.2.7 on 2025-10-22 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_ride_event_rideevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideevent',
            name='id_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='api.ride'),
        ),
    ]
